language: node_js

node_js:
- '4'
- '5'
- '6'

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9

before_script:
- strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX
- npm install
- npm run lint

script:
- npm test
