language: node_js

node_js:
- '4'
- '5'
- '6'

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-4.9-dev

before_script:
- npm install
- npm run lint

script:
- npm test
